name: files-gh-proxy-update

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight
  workflow_dispatch: # Allow manual triggering
  push:
    paths:
      - 'scripts/fresh-gh-proxy.py'
      - 'scripts/ghproxy-url-latest.txt'
      - '.github/workflows/files-gh-proxy-update.yml'
  pull_request:
    paths:
      - 'scripts/fresh-gh-proxy.py'
      - 'scripts/ghproxy-url-latest.txt'
      - '.github/workflows/files-gh-proxy-update.yml'
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright beautifulsoup4
          playwright install
          playwright install-deps

      - name: Run fresh-gh-proxy script
        run: python scripts/fresh-gh-proxy.py

      - name: Commit and push changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add bucket scripts/ghproxy-url*.txt
            git commit -m "Update GitHub proxy domains"
            git push
          else
            echo "No changes to commit"
          fi
